### ISSUE TITLE
[BUG] Failed resolution of: Landroid/graphics/Typeface$Builder;

### ISSUE THREAD

**Issue by ahmed-shehataa** [stipop-development/Stipop_SDK_Android#25]
**Describe the bug**
When try to run the app on android 5 this crash happens.

**Screenshots**
[https://drive.google.com/file/d/1QGL-iY-v6drqVrcGjq1V4jvXsCGRhvvy/view?usp=sharing](https://drive.google.com/file/d/1QGL-iY-v6drqVrcGjq1V4jvXsCGRhvvy/view?usp=sharing)
**Additional context**

**Comment by hojunjeong90** [comment]
This is because Typeface.Builder is not provided in Android O version or lower. 
To solve this problem, I will make compatibility task. 
For now, I block this issue so it doesn't crash. (on 0.2.0)
Thanks for letting me know!
